params = {
    "OUTPUT_DATA_ROOT": "/invalid/path/to/data",
    "INPUT_DATA_ROOT": "/home/nealsiekierski/caffe/data/SegmentVesselsUsingNeuralNetworks",
    "TYPE_SUBDIR_STRUCTURE": "*",
    "TYPES": {
        "Controls": "controls",
        "LargeTumor": "tumors",
    },
    "NETWORK_DESIGN": "xyz",
    "PATCH_RADIUS": 31,
    "RESAMPLE_SPACING": null,
    "SMOOTHING_RADIUS": 2,
    "POSITIVE_PATCHES_PER_INPUT_FILE": 5000,
    "NEGATIVE_TO_POSITIVE_RATIO": 1.0,
    "NUM_TRAIN_EPOCHS": 12,
    "NUM_TEST_EPOCHS": 1,
    "TRAIN_BATCH_SIZE": 768,
    "TEST_BATCH_SIZE": 768,
    "DEPLOY_BATCH_SIZE": 1024,
    "DEPLOY_TOP_WINDOW": 5,
    "SOLVER_TYPE": "SGD",
    "SOLVER_PARAMS": {
        "MOMENTUM": 0.9,
    },
    "BASE_LR": 0.2,
    "WEIGHT_DECAY": 0.0001,
    "GAMMA": 0.02,
    "VESSEL_SEED_PROBABILITY": 0.95,
    "VESSEL_SCALE": 0.1,
}
