cmake_minimum_required(VERSION 2.6)

set( CTEST_SITE "${SITE_NAME}" )
set( CTEST_BUILD_NAME "${SITE_BUILD_NAME}" )
set( CTEST_BUILD_CONFIGURATION "${SITE_BUILD_TYPE}" )

set( CTEST_TEST_TIMEOUT 1500 )

set( CTEST_CMAKE_GENERATOR "Unix Makefiles" )
set( CTEST_NOTES_FILES "${SITE_SCRIPT_DIR}/${CTEST_SCRIPT_NAME}" )
set( CTEST_SOURCE_DIRECTORY "${SITE_SOURCE_DIR}" )
set( CTEST_BINARY_DIRECTORY "${SITE_BINARY_DIR}/TubeTK-Build" )

set( ENV{DISPLAY} ":0" )

set( CTEST_BUILD_COMMAND "${SITE_MAKE_COMMAND}" )
set( CTEST_CMAKE_COMMAND "${SITE_CMAKE_COMMAND}" )
set( CTEST_QMAKE_COMMAND "${SITE_QMAKE_COMMAND}" )
set( CTEST_UPDATE_COMMAND "${SITE_UPDATE_COMMAND}" )

#
# Coverage
#
set( CTEST_COVERAGE_COMMAND "${SITE_COVERAGE_COMMAND}" )
set( COVERAGE_OPTIONS "-fprofile-arcs -ftest-coverage -lgcov" )

file(WRITE "${CTEST_BINARY_DIRECTORY}/CMakeCache.txt" "
  SITE:STRING=${CTEST_SITE}
  BUILDNAME:STRING=${CTEST_BUILD_NAME}
  BUILD_TESTING:BOOL=ON
  BUILD_SHARED_LIBS:BOOL=ON
  MAKECOMMAND:STRING=${CTEST_BUILD_COMMAND}
  CMAKE_BUILD_TYPE:STRING=${CTEST_BUILD_CONFIGURATION}
  CMAKE_CXX_FLAGS:STRING=-fPIC -fdiagnostics-show-option -W -Wall -Wextra -Wshadow -Wno-system-headers -Wwrite-strings -Wno-deprecated -Woverloaded-virtual ${COVERAGE_OPTIONS} )
  CMAKE_C_FLAGS:STRING=-fPIC -fdiagnostics-show-option -W -Wall -Wextra -Wshadow -Wno-system-headers -Wwrite-strings ${COVERAGE_OPTIONS} )
  QT_QMAKE_EXECUTABLE:FILEPATH=${CTEST_QMAKE_COMMAND}
  USE_SYSTEM_ITK:BOOL=ON
  TubeTK_USE_SUPERBUILD:BOOL=OFF
  TubeTK_USE_KWSTYLE:BOOL=ON
  CTK_DIR:PATH=${SITE_BINARY_DIR}/CTK-Build
  ITK_DIR:PATH=${SITE_BINARY_DIR}/Insight-Build
  GenerateCLP_DIR:PATH=${SITE_BINARY_DIR}/GenerateCLP-Build
  OpenIGTLink_DIR:PATH=${SITE_BINARY_DIR}/OpenIGTLink-Build
  ")

ctest_start(Nightly)
ctest_configure(BUILD "${CTEST_BINARY_DIRECTORY}")
ctest_read_custom_files("${CTEST_BINARY_DIRECTORY}")
ctest_test(BUILD "${CTEST_BINARY_DIRECTORY}")
ctest_coverage(BUILD "${CTEST_BINARY_DIRECTORY}")
EXECUTE_PROCESS(COMMAND ${SITE_MAKE_COMMAND} -C "${CTEST_BINARY_DIRECTORY}" StyleCheck)
ctest_submit()

