/*=========================================================================

Library:   TubeTK

Copyright 2010 Kitware Inc. 28 Corporate Drive,
Clifton Park, NY, 12065, USA.

All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=========================================================================*/

#include "tubeMessage.h"

#include <itkImageFileReader.h>
#include <itkImageFileWriter.h>
#include "itktubeConvertTubeGraphToImageFilter.h"

#include "ConvertTubeGraphToImageCLP.h"

template< class TPixel, unsigned int VDimension >
int DoIt( int argc, char * argv[] );

// Must follow include of "...CLP.h" and forward declaration of int DoIt( ... ).
#include "tubeCLIHelperFunctions.h"

int main( int argc, char * argv[] )
{
  PARSE_ARGS;
  return tube::ParseArgsAndCallDoIt( inCentroidsFile, argc, argv );
}


template< class TPixel, unsigned int VDimension >
int DoIt( int argc, char * argv[] )
{
  PARSE_ARGS;

  std::stringstream logMsg;

  typedef itk::Image< float, VDimension >       ImageType;
  typedef itk::Image< TPixel, VDimension >      CVTImageType;
  typedef itk::ImageFileReader< CVTImageType >  ImageReaderType;

  typename ImageReaderType::Pointer imageReader = ImageReaderType::New();

  // Read image file generated by CVT
  imageReader->SetFileName( inCentroidsFile.c_str() );
  imageReader->Update();
  typename CVTImageType::Pointer cvtImage = imageReader->GetOutput();

  typedef itk::tube::ConvertTubeGraphToImageFilter< CVTImageType, ImageType >
    ConvertTubeGraphToImageFilterType;
  typename ConvertTubeGraphToImageFilterType::Pointer filter =
    ConvertTubeGraphToImageFilterType::New();
  filter->SetInput( cvtImage );
  filter->SetInGraphFileName( inGraphFile );
  filter->Update();

  typedef itk::ImageFileWriter< ImageType > ImageWriterType;
  typename ImageWriterType::Pointer imageWriter;
  std::string filename;

  filename = outImageFile + ".mat.mha";
  imageWriter = ImageWriterType::New();
  imageWriter->SetFileName( filename.c_str() );
  imageWriter->SetInput( filter->GetAdjacencyMatrixImage() );
  imageWriter->Write();

  filename = outImageFile + ".brc.mha";
  imageWriter = ImageWriterType::New();
  imageWriter->SetFileName( filename.c_str() );
  imageWriter->SetInput( filter->GetBranchnessImage() );
  imageWriter->Write();

  filename = outImageFile + ".rot.mha";
  imageWriter = ImageWriterType::New();
  imageWriter->SetFileName( filename.c_str() );
  imageWriter->SetInput( filter->GetRadiusImage() );
  imageWriter->Write();

  filename = outImageFile + ".cnt.mha";
  imageWriter = ImageWriterType::New();
  imageWriter->SetFileName( filename.c_str() );
  imageWriter->SetInput( filter->GetCentralityImage() );
  imageWriter->Write();

  return EXIT_SUCCESS;
}
