name: clang-format linter

on: [push,pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: InsightSoftwareConsortium/ITKClangFormatLinterAction@master
