name: clang-format linter

on: [push,pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2

    - uses: InsightSoftwareConsortium/ITKClangFormatLinterAction@master
      with:
        itk-branch: master
