name: WebAssembly

on: [push,pull_request]

jobs:
  build-wasm:
    name: "Build WebAssembly"
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install
      run: |
        npm install

    - name: Build
      run: |
        npm run build
